### PR TITLE
Website docs

### LINKED ISSUE #8: Better documentation
@pedsmoreira what you think about a site with `battlecry` documentation?

https://github.com/facebook/Docusaurus

### PR DESCRIPTION
**Pull request by raulfdm**
Closes #8 

screencapture-localhost-3000-2018-12-16-17_27_23

> Online Demo https://proposal-docs.surge.sh

Hey @pedsmoreira , how you doing?

So, it's been a long time since I'd proposed a website to improve the docs. 

Today I found a really nice tool built in VueJS to build docs way simpler than Docssauros, it's [Docsify](https://docsify.js.org). So I've wrote this proposal to see what you think about it.

There was two ways to approach it:
1. Keep only a single file `README` and keep the automatic `sidebar` generation from Docsify;
2. Split `README` into small files and customize the `sidebar`.

I decided for the second one because in mind mind it's clear both the sidebar and the files. I also think it's nicer to maintain.

## About the structure

First of all I'd suggest you take a brief look into Docsify documentation, it's clear and neat to understand. Then, I'll try to explain you a little bit how it works.

In a nutshell, Docsify uses `index.html` as entry point. So, there's the place we import the styles, plugins and also configure the tool to work.

After loaded and based on our configuration, it loads the `README.md` and the `_sidebar.md` files to build the page. Then, we have the links for the other doc files.

### docs folder
To make it better to isolate from everything, I've defined `docs` folder as the files holder.

### 2 READMES?

Unfortunately I didn't find a way to use the `README` from the root inside `docs` folder. To avoid double maintenance, I've created a very simple script to copy'n'paste this file cross the project.

>⚠️I didn't defined any hook to trigger this script. So I'd suggest you think about the deploy process and see the best moment to call it (e.g. CI file, post/pre script, etc.)

## No Building
That's it. Docsify doesn't have build process at all. The only thing you have to is host `docs/` folder in some http server.

## Deploy
There's a lot of different ways to deploy it. For my personal notebook using Docsify I've chosen Netlify because it's goddamm easy and every time I merge something to `master`, it trigger my deploy.

However, you can also choose another option. Check it out [here](https://docsify.js.org/#/deploy).

> To present to you the docs I chose [Surge](http://surge.sh).

## After words

That's it man, hope you like it! If you have any further question just let me know :)

### CODE REVIEW

**Comment by pedsmoreira** [comment]
Hey @raulfdm, I'm doing well and you?

These docs look amazing! I'll review the changes and try to get battlecry.js domain. 

I like the idea of having the docs separated in sub menus. I can see a sequence of tutorials for beginners (suggest by on #9) fitting very well in it. Perhaps over time there could even be a submenu with examples in several languages.

Thanks for your contribution!

**Comment by raulfdm** [comment]
Hey man.. I'm doing super, thanks.

Nice. About the translations it's quite nice because as I could check it, docsify is already prepared to handle it. It's only about add a config and another folder like `docs-ptBR` or any language.

Glad you like it! 👍

**Comment by raulfdm** [comment]
Oh, almost forgot.

Maybe you'd see analytics about the website traffic.
There's a plugin to easy add GA tag (https://docsify.js.org/#/plugins?id=google-analytics)

**Comment by pedsmoreira** [comment]
Cool! It's nice to know that there's a simple way to add translations.

I merged, configured the deploy process through Netlify and added GA, now I'm waiting for the .js.org domain PR to be merged.

Thanks!

**Pull request merged**
