### PR TITLE
Upgrade to Babel 7 & package install fix

### PR DESCRIPTION
**Pull request by vadistic**
Ciao, 

I'm so glad I found this project yesterday -  amazing thing!

One problem - when installing via npm/yarn it simply did not run (at least on my Windows) 😭 

```
Error: Cannot find module 'samba'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\samba\bin\samba.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

It looks, that `babel-plugin-module-resolver` did not really worked for me. I symlinked cloned repro, and after taking samba for a spin and seeing how great it works - I thought I would fix it, before investing time in building some scripts for my personal projects.

**Here's what I did:**
1) Cut `babel-plugin-module-resolver` - it was really only used in one line in bin/samba.js and probably caused aforementioned issue. Also, as not part of official @babel monorepo it's not so cool/safe to use, esspecially with Babel 7 [open Issue about Babel 7](https://github.com/tleunen/babel-plugin-module-resolver/issues/274)

    - I simply used this to resolve Samba in `bin`
```node
const Samba = require(`${__dirname}/../src`).Samba;
```

2) As I was tuning babel, I thought I could bump it to Babel 7 
    - It's in beta for last half a year, but [rc should be any day now](https://github.com/babel/babel/milestone/15). 
    - Babel 7 moved all deps to monorepo @babel so I changed them. 
    - The preset is env & flow + plugins for proposal features you used. I dropped preset-stage-0 as not really necessary.
    - Added babel-core@bridge (backward api compatibility layer) for babel-jest that has babel-core in deps

3) After all that it looked that registerBabel.js was ready for some cutting
    - module resolver plugin is gone
    - path mapping is not necessary, because shape of babelrc match exactly what should be passed to register (what a surprise 😄 ) ` i.e. "plugins": ["@babel/plugin-proposal-class-properties"]`
    - ignore option only support array now, so ignore fn needed to be transformed into some regex/glob pattern. I looked it up and 'node_modules' are default ignored and [ignore pattern match is done relative to cwd()](https://github.com/babel/babel/pull/5487) - so it look the whole thing could also be cut.

4) I wanted to make a commit and outdated 'lint-staged' did not think node 10 > node 6 so I upgraded it too.

What do you think?

### CODE REVIEW

**Comment by pedsmoreira** [comment]
Hey Jakub, I'm glad you liked the project and decided to contribute :). I hope it will speed up development for your personal projects as much as it has for me.

Your PR looks great, and upgrading to Babel 7 is definitely a good thing! I'll test it later and if nothing breaks I'll merge it.

**Comment by vadistic** [comment]
I just noticed it's still not fixed. I jumped a bit and did not thought about test and samba dirs that rely on this module resolver plugin ... 

Surprisingly tests passes so it looks  recursive samba module reference is all ok even without setting module aliases.

I'll try to tweak it and see if I can solve it (maybe the issue is only on my machine, need to try) and submit PR revision and if not I'll cut this PR only for babel upgrade, because it's a breeze,

**Comment by pedsmoreira** [comment]
Hey @vadistic,

Just tested and unfortunately it didn't work. Inside the `samba` itself it works, but when I tried going to another folder and calling `sb g init`, it doesn't resolve the paths as intended.

The babel setup on this project is quite tricky. I guess it would be good to have a more detailed explanation about it somewhere.

### About the tests

I have to admit that I'm not quite sure how 'samba' gets resolved on the tests. Seems to be some serious wizardry 🍀 

The tests that are in place are only for `File` and they don't test commands directly, so the tests can pass and the actual commands still fail. It would be nice to have tests that actually run commands at 
some point.

### Testing from scratch

I tried setting up my environment from scratch and `npm install -g samba` and it works for me, but I'm on OSX, so I'm not sure it counts since you had issues on Windows.

Cloning the repo however, brought to my attention to the fact that there were steps missing on the Contributing.md guide, so I updated it. For `samba` to work with `npm link`, you need to perform both `npm link` and `npm link samba`.

https://github.com/pedsmoreira/samba/blob/master/CONTRIBUTING.md#development

### About module-resolver

I guess it still needs to be there to resolve which files should be parsed by `babel` and which don't. I wasn't quite sure if Babel 7 would work without it, since there are differences from Babel 6 and Babel 7, but looks like it still needs the module resolver.

Because `samba` is installed and gets placed inside `node_modules` somewhere, babel understands that it doesn't need to be parsed, therefore, no files inside `src/` and `samba/` get parsed, so they throw syntax errors. The same would be true if you downloaded a set of commands and tried to import them on your `samba-setup.js`.

Also, `samba` is imported from generators inside each individual project and, because `samba` is not installed on the project itself, not having the `alias` implies that Babel can't find it.

_I'm not a Babel expert and I'm still a bit confused with all the changes that happened between Babel 6 and 7, so some of these statements above may not be true for Babel 7 anymore._

### Why not just pre-compile it?

The idea is that both the `samba` module, and everything that's inside a `samba/` folder (generators), should get parsed by babel-register. We wouldn't need to do that if those files were compiled before being published to `npm`, but the intention is to make development easier, so the more steps are needed in order to make it work, the less people will be encouraged to use Samba. It's important to take into account that this project is intended to serve all languages and frameworks, so not everyone will be a savvy javascript developer.

### ...

Thanks for all your effort to figure this stuff out @vadistic.

Windows can be tricky with these things, so I'll see if I can get my hands on a Windows machine to test this module resolution issue. If you can find the fix that would be awesome, in that case, please update this PR :)

If you still want to pursue upgrading the project to Babel 7, I encourage you to do so. I'm not sure it would be possible at this moment, given the issue with babel-loader you pointed, but it would be nice to have Babel 7.

**Comment by vadistic** [comment]
Thank you for really detailed explanation. 

Anyway, I'll try to fix that, but till now I have moderate luck :)

My current commit is working from github install by using kind of a hack in babelResolver to look for dependencies in partent - global node_modules (test also pass, I undid my commit and this confused travis)

```
function buildPath(name) {
  return normalize(`${__dirname}/../../${name}`);
}
```

There should be a cleaner way to do that and, because now it breaks running samba locally/via yarn link... And it breaks my ignore glob `**/samba/node_modules/**` for babel.

But I think I'm closer 😄

**Comment by pedsmoreira** [comment]
Hey @vadistic,

I got a Windows machine to perform some tests and I believe I found the issue.

- Windows paths can be `\\` or `\` instead of `/`, here's the fix:
https://github.com/pedsmoreira/samba/blob/master/bin/registerBabel.js#L7

- require('samba') did not work on bin/samba.js on Windows. Seems like the symlinking is tricky there, here's the fix:
https://github.com/pedsmoreira/samba/blob/master/bin/samba.js#L6

It's still necessary to have `samba` linked through babel, since we perform `import 'samba'` from the generators and samba-setup.

Please let me know if this fixes your errors and feel free to continue the Babel 7 upgrade if you wish to.

**Comment by pedsmoreira** [comment]
Since there have been no more updates, I'm closing this PR.

**Pull request closed without merging**
